---
- hosts: runner
  name: prepare vagrant box
  become_user: root
  vars_prompt:
    - name: git_branch
      prompt: "git branch (e.g. master)"
      private: false
  pre_tasks:
    - set_fact:
        template_box_name: "ci-{{ git_branch }}-f25"
  roles:
    - box/prepare

# HACK: workaround to install Python2 that is still required by Ansible
- hosts: image_box
  gather_facts: false
  tasks:
    - name: install python and deps for ansible modules
      raw: test -e /usr/bin/python || dnf install -y python2 python2-dnf libselinux-python
    - name: gather facts
      setup:

- hosts: image_box
  name: modify vagrant box template
  vars_prompt:
    - name: git_branch
      prompt: "git branch (e.g. master)"
      private: false
    - name: freeipa_copr
      prompt: "FreeIPA copr (e.g. @freeipa/freeipa-master)"
      private: false
  roles:
    - role: builder
      git_version: "{{ git_branch }}"
    - role: machine

- hosts: runner
  name: package template box
  become_user: root
  roles:
    - box/package
